### PR TITLE
Updated mod to work with Factorio 0.16

### PR DESCRIPTION
**Pull request by jimmyjon711**
I have also updated the Storage mod, but I was not able to fork that repo and can be found here https://github.com/jimmyjon711/FactorioExtended-Storage

Please let me know if you are planning on keeping this mod up to date.

### CODE REVIEW

**Comment by flexoo** [comment]
Hi, also the undergroundbelts need to be in fast_replaceable_group = "transport-belt"

**Comment by jimmyjon711** [comment]
@flexoo This has been added to this pull request, its in the enitity-transport.lua file

**Comment by flexoo** [comment]
nice, what do you think about letting splitters in splitter fast replaceable group? I know it got changed, but personally I like that better.

**Comment by jimmyjon711** [comment]
@flexoo for now I made it the same as how splitters fast replace in vanilla for 0.16

**Comment by flexoo** [comment]
yeah, saw it, fair enough. Hopefully it gets updated soon in the first place

**Comment by jimmyjon711** [comment]
@flexoo ya i hope so to, if there is not any activity soon I will probably post the updated version to mod portal citing him as original author

**Comment by flexoo** [comment]
that are good news, so this little gem wont get left behind.

**Pull request closed without merging**
